export LAMBDA_RUNTIME_LIB_DIR="${LAMBDA_RUNTIME_DIR}/lib"
export LAMBDA_RUNTIME_BIN_DIR="${LAMBDA_RUNTIME_DIR}/bin"
export LAMBDA_RUNTIME_PHP_INI_PATH="${LAMBDA_RUNTIME_DIR}/etc/php.ini"
export LAMBDA_RUNTIME_PHP_INI_SCAN_DIR="${LAMBDA_RUNTIME_DIR}/etc/php.d"
export LAMBDA_RUNTIME_PHP_CACHE_DIR="${LAMBDA_RUNTIME_DIR}/etc/php.d"

export LD_LIBRARY_PATH="${LAMBDA_RUNTIME_LIB_DIR}:${LD_LIBRARY_PATH}"
export PATH="${LAMBDA_RUNTIME_BIN_DIR}:${PATH}"
export PHPRC="${LAMBDA_RUNTIME_PHP_INI_PATH}"
export PHP_INI_SCAN_DIR="${LAMBDA_RUNTIME_PHP_INI_SCAN_DIR}"

mkdir -p "${LAMBDA_RUNTIME_PHP_CACHE_DIR}"

